language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - cmake
            - libgoogle-glog-dev
            - libatlas-base-dev
            - libeigen3-dev
            - libsuitesparse-dev
            - libgtest-dev
env:
- MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#branches:
#  only:
#  - master

before_script:
    - wget http://ceres-solver.org/ceres-solver-1.13.0.tar.gz
    - tar zxf ceres-solver-1.13.0.tar.gz
    - cd ceres-solver-1.13.0
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - sudo make install

    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - ./tests/run_tests

before_install:
- eval "${MATRIX_EVAL}"
